 Rusty Bargain used car sales service is developing an app to attract new customers. In that app, you can quickly find out the market value of your car. You have access to historical data: technical specifications, trim versions, and prices. You need to build the model to determine the value.



 Rusty Bargain is interested in:



 - the quality of the prediction;

 - the speed of the prediction;

 - the time required for training

In [1]:
# %%
import matplotlib.pyplot as plt
import pandas as pd
pd.set_option('display.max_columns', None)
import numpy as np

 # 1. Data preparation

 ### Downloading

In [2]:
# %%
data = pd.read_csv('https://code.s3.yandex.net/datasets/autos.csv')
print(data.shape)
data.head()

(354369, 16)

,DateCrawled,Price,VehicleType,RegistrationYear,Gearbox,Power,Model,Kilometer,RegistrationMonth,FuelType,Brand,Repaired,DateCreated,NumberOfPictures,PostalCode,LastSeen
0,2016-03-24 11:52:17,480,NaN,1993,manual,0,golf,150000,0,petrol,volkswagen,NaN,2016-03-24 00:00:00,0,70435,2016-04-07 03:16:57
1,2016-03-24 10:58:45,18300,coupe,2011,manual,190,NaN,125000,5,gasoline,audi,yes,2016-03-24 00:00:00,0,66954,2016-04-07 01:46:50
2,2016-03-14 12:52:21,9800,suv,2004,auto,163,grand,125000,8,gasoline,jeep,NaN,2016-03-14 00:00:00,0,90480,2016-04-05 12:47:46
3,2016-03-17 16:54:04,1500,small,2001,manual,75,golf,150000,6,petrol,volkswagen,no,2016-03-17 00:00:00,0,91074,2016-03-17 17:40:17
4,2016-03-31 17:25:20,3600,small,2008,manual,69,fabia,90000,7,gasoline,skoda,no,2016-03-31 00:00:00,0,60437,2016-04-06 10:17:21

 ### Preprocessing

 Unnecessary features (can't be used in the product):



 - dates

 - zip-code

In [3]:
# %%
data = data.drop(['DateCrawled', 'DateCreated', 'PostalCode', 'LastSeen'], axis=1)
data.head()

,Price,VehicleType,RegistrationYear,Gearbox,Power,Model,Kilometer,RegistrationMonth,FuelType,Brand,Repaired,NumberOfPictures
0,480,NaN,1993,manual,0,golf,150000,0,petrol,volkswagen,NaN,0
1,18300,coupe,2011,manual,190,NaN,125000,5,gasoline,audi,yes,0
2,9800,suv,2004,auto,163,grand,125000,8,gasoline,jeep,NaN,0
3,1500,small,2001,manual,75,golf,150000,6,petrol,volkswagen,no,0
4,3600,small,2008,manual,69,fabia,90000,7,gasoline,skoda,no,0

In [4]:
# %%
data['NumberOfPictures'].value_counts()

NumberOfPictures
0    354369
Name: count, dtype: int64

 Deleting constant feature

In [5]:
# %%
data = data.drop(['NumberOfPictures'], axis=1)
data.head()

,Price,VehicleType,RegistrationYear,Gearbox,Power,Model,Kilometer,RegistrationMonth,FuelType,Brand,Repaired
0,480,NaN,1993,manual,0,golf,150000,0,petrol,volkswagen,NaN
1,18300,coupe,2011,manual,190,NaN,125000,5,gasoline,audi,yes
2,9800,suv,2004,auto,163,grand,125000,8,gasoline,jeep,NaN
3,1500,small,2001,manual,75,golf,150000,6,petrol,volkswagen,no
4,3600,small,2008,manual,69,fabia,90000,7,gasoline,skoda,no

In [6]:
# %%
data.describe()

,Price,RegistrationYear,Power,Kilometer,RegistrationMonth
count,354369.000000,354369.000000,354369.000000,354369.000000,354369.000000
mean,4416.656776,2004.234448,110.094337,128211.172535,5.714645
std,4514.158514,90.227958,189.850405,37905.341530,3.726421
min,0.000000,1000.000000,0.000000,5000.000000,0.000000
25%,1050.000000,1999.000000,69.000000,125000.000000,3.000000
50%,2700.000000,2003.000000,105.000000,150000.000000,6.000000
75%,6400.000000,2008.000000,143.000000,150000.000000,9.000000
max,20000.000000,9999.000000,20000.000000,150000.000000,12.000000

 The registration year of 1000 and 9999 is clearly incorrect, delete entries with incorrect values.



 Power cannot be equal to 0.

In [7]:
# %%
data = data[data['RegistrationYear'] < 2050]
data = data[data['RegistrationYear'] > 1900]
data = data[data['Power'] != 0]

data.reset_index()
data.shape

(314100, 11)

In [8]:
# %%
data.isna().sum(axis=0)

Price                    0
VehicleType          22818
RegistrationYear         0
Gearbox               6501
Power                    0
Model                13395
Kilometer                0
RegistrationMonth        0
FuelType             21212
Brand                    0
Repaired             49708
dtype: int64

 Missing values are only in categorical columns. They can be filled with a new value "unknown".

In [9]:
# %%
data = data.fillna('unknown')
data.isna().sum(axis=0)

Price                0
VehicleType          0
RegistrationYear     0
Gearbox              0
Power                0
Model                0
Kilometer            0
RegistrationMonth    0
FuelType             0
Brand                0
Repaired             0
dtype: int64

 ### Feature encoding

In [12]:
# %%
categorical_features = [
    'VehicleType',
    'Gearbox', 
    'Model',
    'FuelType', 
    'Brand',
    'Repaired', 
]

 **OHE-encoding**



 Here, some features will have to be removed due to the large number of values

In [14]:
# %%
for feature in categorical_features:
    print(data[feature].value_counts())

VehicleType
sedan          84852
small          71522
wagon          60508
bus            26530
unknown        22818
convertible    19034
coupe          15078
suv            11115
other           2643
Name: count, dtype: int64
Gearbox
manual     246097
auto        61502
unknown      6501
Name: count, dtype: int64
Model
golf                  26760
other                 21248
3er                   18226
unknown               13395
polo                  11455
                      ...
i3                        5
samara                    5
rangerover                3
serie_3                   3
range_rover_evoque        2
Name: count, Length: 250, dtype: int64
FuelType
petrol      196358
gasoline     90723
unknown      21212
lpg           4913
cng            506
hybrid         207
other          103
electric        78
Name: count, dtype: int64
Brand
volkswagen        68805
opel              34902
bmw               33876
mercedes_benz     28512
audi              27075
ford              21900
renault           14956
peugeot            9816
fiat               8178
seat               6292
skoda              5103
mazda              4977
smart              4657
citroen            4505
nissan             4268
toyota             4160
hyundai            3234
mini               3080
volvo              2937
mitsubishi         2653
honda              2546
kia                2205
alfa_romeo         2090
suzuki             2052
sonstige_autos     1979
chevrolet          1529
chrysler           1239
dacia               829
subaru              682
daihatsu            658
porsche             645
jeep                601
saab                493
land_rover          476
jaguar              448
daewoo              434
lancia              414
rover               404
trabant             327
lada                163
Name: count, dtype: int64
Repaired
no         233116
unknown     49708
yes         31276
Name: count, dtype: int64

In [15]:
# %%
data_ohe = data.drop(['Model', 'Brand'], axis=1)
data_ohe = pd.get_dummies(data_ohe)
print(data_ohe.shape)
data_ohe.head()

(314100, 28)

,Price,RegistrationYear,Power,Kilometer,RegistrationMonth,VehicleType_bus,VehicleType_convertible,VehicleType_coupe,VehicleType_other,VehicleType_sedan,VehicleType_small,VehicleType_suv,VehicleType_unknown,VehicleType_wagon,Gearbox_auto,Gearbox_manual,Gearbox_unknown,FuelType_cng,FuelType_electric,FuelType_gasoline,FuelType_hybrid,FuelType_lpg,FuelType_other,FuelType_petrol,FuelType_unknown,Repaired_no,Repaired_unknown,Repaired_yes
1,18300,2011,190,125000,5,False,False,True,False,False,False,False,False,False,False,True,False,False,False,True,False,False,False,False,False,False,False,True
2,9800,2004,163,125000,8,False,False,False,False,False,False,True,False,False,True,False,False,False,False,True,False,False,False,False,False,False,True,False
3,1500,2001,75,150000,6,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False,True,False,True,False,False
4,3600,2008,69,90000,7,False,False,False,False,False,True,False,False,False,False,True,False,False,False,True,False,False,False,False,False,True,False,False
5,650,1995,102,150000,10,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,True

 Ordinal encoding

In [16]:
# %%
from sklearn.preprocessing import OrdinalEncoder

data[categorical_features] = OrdinalEncoder().fit_transform(data[categorical_features])

data.head()

,Price,VehicleType,RegistrationYear,Gearbox,Power,Model,Kilometer,RegistrationMonth,FuelType,Brand,Repaired
1,18300,2.0,2011,1.0,190,227.0,125000,5,2.0,1.0,2.0
2,9800,6.0,2004,0.0,163,117.0,125000,8,2.0,14.0,1.0
3,1500,5.0,2001,1.0,75,116.0,150000,6,6.0,38.0,0.0
4,3600,5.0,2008,1.0,69,101.0,90000,7,2.0,31.0,0.0
5,650,4.0,1995,1.0,102,11.0,150000,10,6.0,2.0,2.0

 ### Split into train-validation-test

In [17]:
# %%
from sklearn.model_selection import train_test_split

index_train_valid, index_test = train_test_split(data.index, test_size=0.2, random_state=12345)
index_train, index_valid = train_test_split(index_train_valid, test_size=0.25, random_state=54321)

data_train = data.loc[index_train]
data_valid = data.loc[index_valid]
data_test = data.loc[index_test]

data_ohe_train = data_ohe.loc[index_train]
data_ohe_valid = data_ohe.loc[index_valid]
data_ohe_test = data_ohe.loc[index_test]

print(data_train.shape)
print(data_valid.shape)
print(data_test.shape)

print(data_ohe_train.shape)
print(data_ohe_valid.shape)
print(data_ohe_test.shape)

(188460, 11)
(62820, 11)
(62820, 11)
(188460, 28)
(62820, 28)
(62820, 28)

 # 2. Model training

In [18]:
# %%
from sklearn.metrics import mean_squared_error

def rmse(y, a):
    return mean_squared_error(y, a)**0.5

 Constant model

In [19]:
# %%
pred_mean = np.ones(data['Price'].shape) * data['Price'].mean()
print(rmse(data['Price'], pred_mean))

4590.240919951061

 ### Models with OHE

In [20]:
# %%
features_train = data_ohe_train.drop(['Price'], axis=1)
target_train = data_ohe_train['Price']
features_valid = data_ohe_valid.drop(['Price'], axis=1)
target_valid = data_ohe_valid['Price']
features_test = data_ohe_test.drop(['Price'], axis=1)
target_test = data_ohe_test['Price']

 **Linear regression**

In [21]:
# %%

from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(features_train, target_train)

LinearRegression()

In [22]:
# %%

pred_train = model.predict(features_train)
pred_valid = model.predict(features_valid)
pred_test = model.predict(features_test)

In [23]:
# %%
print("Train RMSE:", rmse(target_train, pred_train).round(5))
print("Valid RMSE:", rmse(target_valid, pred_valid).round(5))
print("Test RMSE: ", rmse(target_test, pred_test).round(5))

Train RMSE: 3238.30929
Valid RMSE: 3216.58303
Test RMSE:  3223.39036

 ### Models with ordinal encoding

In [24]:
# %%
features_train = data_train.drop(['Price'], axis=1)
target_train = data_train['Price']
features_valid = data_valid.drop(['Price'], axis=1)
target_valid = data_valid['Price']
features_test = data_test.drop(['Price'], axis=1)
target_test = data_test['Price']

 **Random forrest**

In [25]:
# %%
from sklearn.ensemble import RandomForestRegressor

for depth in [1, 2, 4, 6, 8, None]:
    model = RandomForestRegressor(max_depth=depth, n_estimators=100)
    model.fit(features_train, target_train)
    
    pred_train = model.predict(features_train)
    pred_valid = model.predict(features_valid)
    print("Depth:", depth)
    print("Train RMSE:", rmse(target_train, pred_train).round(5))
    print("Valid RMSE:", rmse(target_valid, pred_valid).round(5))

Depth: 1
Train RMSE: 3790.22037
Valid RMSE: 3782.29044
Depth: 2
Train RMSE: 3330.0806
Valid RMSE: 3319.26108
Depth: 4
Train RMSE: 2688.14011
Valid RMSE: 2674.87205
Depth: 6
Train RMSE: 2335.3801
Valid RMSE: 2336.725
Depth: 8
Train RMSE: 2099.39466
Valid RMSE: 2124.44798
Depth: None
Train RMSE: 771.17461
Valid RMSE: 1733.3114

In [26]:
# %%

from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor(n_estimators=100, max_depth=None)
model.fit(features_train, target_train)

RandomForestRegressor()

In [27]:
# %%

pred_train = model.predict(features_train)
pred_valid = model.predict(features_valid)
pred_test = model.predict(features_test)

In [28]:
# %%
print("Train RMSE:", rmse(target_train, pred_train).round(5))
print("Valid RMSE:", rmse(target_valid, pred_valid).round(5))
print("Test RMSE: ", rmse(target_test, pred_test).round(5))

Train RMSE: 772.21538
Valid RMSE: 1729.6912
Test RMSE:  1728.29424

 **Gradient boosting LightGBM**

In [29]:
# %%

import lightgbm as lgb

model = lgb.LGBMRegressor(num_iterations=1000, vebose=1, metric='rmse')
model.fit(features_train, target_train, 
          eval_set=(features_valid, target_valid),
          categorical_feature=categorical_features)

/Users/juliokorleone/anaconda3/lib/python3.10/site-packages/lightgbm/engine.py:177: UserWarning: Found `num_iterations` in params. Will use it instead of argument
  _log_warning(f"Found `{alias}` in params. Will use it instead of argument")
/Users/juliokorleone/anaconda3/lib/python3.10/site-packages/lightgbm/basic.py:2065: UserWarning: Using categorical_feature in Dataset.
  _log_warning('Using categorical_feature in Dataset.')
/Users/juliokorleone/anaconda3/lib/python3.10/site-packages/lightgbm/basic.py:2068: UserWarning: categorical_feature in Dataset is overridden.
New categorical_feature is ['Brand', 'FuelType', 'Gearbox', 'Model', 'Repaired', 'VehicleType']
  _log_warning('categorical_feature in Dataset is overridden.\n'
/Users/juliokorleone/anaconda3/lib/python3.10/site-packages/lightgbm/basic.py:1780: UserWarning: Overriding the parameters from Reference Dataset.
  _log_warning('Overriding the parameters from Reference Dataset.')
/Users/juliokorleone/anaconda3/lib/python3.10/site-packages/lightgbm/basic.py:1513: UserWarning: categorical_column in param dict is overridden.
  _log_warning(f'{cat_alias} in param dict is overridden.')

[LightGBM] [Warning] Unknown parameter: vebose
[1]	valid_0's rmse: 4264.82
[2]	valid_0's rmse: 3979.81
[3]	valid_0's rmse: 3731.85
[4]	valid_0's rmse: 3510.76
[5]	valid_0's rmse: 3314.92
[6]	valid_0's rmse: 3143.46
[7]	valid_0's rmse: 2990.73
[8]	valid_0's rmse: 2853.47
[9]	valid_0's rmse: 2736.16
[10]	valid_0's rmse: 2628.56
[11]	valid_0's rmse: 2536.41
[12]	valid_0's rmse: 2453.54
[13]	valid_0's rmse: 2380.55
[14]	valid_0's rmse: 2316.78
[15]	valid_0's rmse: 2259.17
[16]	valid_0's rmse: 2210.47
[17]	valid_0's rmse: 2167.23
[18]	valid_0's rmse: 2129.88
[19]	valid_0's rmse: 2093.37
[20]	valid_0's rmse: 2062.17
[21]	valid_0's rmse: 2034.07
[22]	valid_0's rmse: 2009.03
[23]	valid_0's rmse: 1987.14
[24]	valid_0's rmse: 1969.08
[25]	valid_0's rmse: 1952.24
[26]	valid_0's rmse: 1936.99
[27]	valid_0's rmse: 1923.5
[28]	valid_0's rmse: 1911.9
[29]	valid_0's rmse: 1901.18
[30]	valid_0's rmse: 1891.88
[31]	valid_0's rmse: 1883.81
[32]	valid_0's rmse: 1875.78
[33]	valid_0's rmse: 1868.09
[34]	valid_0's rmse: 1860.96
[35]	valid_0's rmse: 1855.35
[36]	valid_0's rmse: 1848.99
[37]	valid_0's rmse: 1843.87
[38]	valid_0's rmse: 1839.01
[39]	valid_0's rmse: 1834.12
[40]	valid_0's rmse: 1830.2
[41]	valid_0's rmse: 1826.09
[42]	valid_0's rmse: 1822.33
[43]	valid_0's rmse: 1818.8
[44]	valid_0's rmse: 1815.57
[45]	valid_0's rmse: 1812.23
[46]	valid_0's rmse: 1809.91
[47]	valid_0's rmse: 1807.7
[48]	valid_0's rmse: 1804.36
[49]	valid_0's rmse: 1802.35
[50]	valid_0's rmse: 1800.23
[51]	valid_0's rmse: 1798.7
[52]	valid_0's rmse: 1796.4
[53]	valid_0's rmse: 1794.52
[54]	valid_0's rmse: 1792.58
[55]	valid_0's rmse: 1791.33
[56]	valid_0's rmse: 1789.55
[57]	valid_0's rmse: 1788.04
[58]	valid_0's rmse: 1786.15
[59]	valid_0's rmse: 1784.43
[60]	valid_0's rmse: 1783.15
[61]	valid_0's rmse: 1781.57
[62]	valid_0's rmse: 1780.55
[63]	valid_0's rmse: 1778.94
[64]	valid_0's rmse: 1777.26
[65]	valid_0's rmse: 1775.41
[66]	valid_0's rmse: 1774.35
[67]	valid_0's rmse: 1772.85
[68]	valid_0's rmse: 1771.56
[69]	valid_0's rmse: 1770.91
[70]	valid_0's rmse: 1770.02
[71]	valid_0's rmse: 1768.86
[72]	valid_0's rmse: 1768.11
[73]	valid_0's rmse: 1766.88
[74]	valid_0's rmse: 1766
[75]	valid_0's rmse: 1764.5
[76]	valid_0's rmse: 1763.54
[77]	valid_0's rmse: 1762.78
[78]	valid_0's rmse: 1762.28
[79]	valid_0's rmse: 1761.93
[80]	valid_0's rmse: 1761.29
[81]	valid_0's rmse: 1760.85
[82]	valid_0's rmse: 1760.12
[83]	valid_0's rmse: 1759.27
[84]	valid_0's rmse: 1758.55
[85]	valid_0's rmse: 1757.56
[86]	valid_0's rmse: 1756.69
[87]	valid_0's rmse: 1756.26
[88]	valid_0's rmse: 1755.68
[89]	valid_0's rmse: 1755.26
[90]	valid_0's rmse: 1754.65
[91]	valid_0's rmse: 1754.16
[92]	valid_0's rmse: 1753.53
[93]	valid_0's rmse: 1752.7
[94]	valid_0's rmse: 1751.67
[95]	valid_0's rmse: 1751.17
[96]	valid_0's rmse: 1750.54
[97]	valid_0's rmse: 1749.14
[98]	valid_0's rmse: 1748.08
[99]	valid_0's rmse: 1747.67
[100]	valid_0's rmse: 1747.23
[101]	valid_0's rmse: 1745.83
[102]	valid_0's rmse: 1745.56
[103]	valid_0's rmse: 1744.77
[104]	valid_0's rmse: 1744.26
[105]	valid_0's rmse: 1743.49
[106]	valid_0's rmse: 1743.04
[107]	valid_0's rmse: 1741.9
[108]	valid_0's rmse: 1741.38
[109]	valid_0's rmse: 1740.16
[110]	valid_0's rmse: 1739.67
[111]	valid_0's rmse: 1739.27
[112]	valid_0's rmse: 1738.7
[113]	valid_0's rmse: 1738.01
[114]	valid_0's rmse: 1737.54
[115]	valid_0's rmse: 1736.91
[116]	valid_0's rmse: 1736.43
[117]	valid_0's rmse: 1735.95
[118]	valid_0's rmse: 1735.82
[119]	valid_0's rmse: 1735.69
[120]	valid_0's rmse: 1735.3
[121]	valid_0's rmse: 1734.63
[122]	valid_0's rmse: 1733.87
[123]	valid_0's rmse: 1733.59
[124]	valid_0's rmse: 1732.99
[125]	valid_0's rmse: 1732.91
[126]	valid_0's rmse: 1732.19
[127]	valid_0's rmse: 1731.76
[128]	valid_0's rmse: 1731.09
[129]	valid_0's rmse: 1731.09
[130]	valid_0's rmse: 1730.98
[131]	valid_0's rmse: 1730.76
[132]	valid_0's rmse: 1730.41
[133]	valid_0's rmse: 1730.28
[134]	valid_0's rmse: 1729.81
[135]	valid_0's rmse: 1729
[136]	valid_0's rmse: 1728.61
[137]	valid_0's rmse: 1728.03
[138]	valid_0's rmse: 1727.37
[139]	valid_0's rmse: 1726.86
[140]	valid_0's rmse: 1726.61
[141]	valid_0's rmse: 1726.11
[142]	valid_0's rmse: 1725.81
[143]	valid_0's rmse: 1725.63
[144]	valid_0's rmse: 1725.34
[145]	valid_0's rmse: 1724.82
[146]	valid_0's rmse: 1724.51
[147]	valid_0's rmse: 1724.08
[148]	valid_0's rmse: 1723.95
[149]	valid_0's rmse: 1723.46
[150]	valid_0's rmse: 1723
[151]	valid_0's rmse: 1722.87
[152]	valid_0's rmse: 1722.38
[153]	valid_0's rmse: 1722.18
[154]	valid_0's rmse: 1721.83
[155]	valid_0's rmse: 1721.32
[156]	valid_0's rmse: 1721.02
[157]	valid_0's rmse: 1720.42
[158]	valid_0's rmse: 1720.07
[159]	valid_0's rmse: 1719.9
[160]	valid_0's rmse: 1719.36
[161]	valid_0's rmse: 1719.11
[162]	valid_0's rmse: 1718.74
[163]	valid_0's rmse: 1718.15
[164]	valid_0's rmse: 1718.04
[165]	valid_0's rmse: 1717.99
[166]	valid_0's rmse: 1717.79
[167]	valid_0's rmse: 1717.38
[168]	valid_0's rmse: 1716.46
[169]	valid_0's rmse: 1715.97
[170]	valid_0's rmse: 1715.57
[171]	valid_0's rmse: 1715.06
[172]	valid_0's rmse: 1714.8
[173]	valid_0's rmse: 1714.41
[174]	valid_0's rmse: 1714.03
[175]	valid_0's rmse: 1713.83
[176]	valid_0's rmse: 1713.35
[177]	valid_0's rmse: 1712.76
[178]	valid_0's rmse: 1712.55
[179]	valid_0's rmse: 1712.38
[180]	valid_0's rmse: 1712.39
[181]	valid_0's rmse: 1712.4
[182]	valid_0's rmse: 1712.46
[183]	valid_0's rmse: 1712.23
[184]	valid_0's rmse: 1712.12
[185]	valid_0's rmse: 1711.84
[186]	valid_0's rmse: 1711.76
[187]	valid_0's rmse: 1711.61
[188]	valid_0's rmse: 1711.45
[189]	valid_0's rmse: 1711.25
[190]	valid_0's rmse: 1711.16
[191]	valid_0's rmse: 1711.09
[192]	valid_0's rmse: 1710.95
[193]	valid_0's rmse: 1710.58
[194]	valid_0's rmse: 1710.62
[195]	valid_0's rmse: 1710.35
[196]	valid_0's rmse: 1710.07
[197]	valid_0's rmse: 1709.83
[198]	valid_0's rmse: 1709.51
[199]	valid_0's rmse: 1709.36
[200]	valid_0's rmse: 1708.59
[201]	valid_0's rmse: 1708.07
[202]	valid_0's rmse: 1708.12
[203]	valid_0's rmse: 1707.79
[204]	valid_0's rmse: 1707.23
[205]	valid_0's rmse: 1706.85
[206]	valid_0's rmse: 1706.51
[207]	valid_0's rmse: 1706.53
[208]	valid_0's rmse: 1706.44
[209]	valid_0's rmse: 1706.41
[210]	valid_0's rmse: 1706.04
[211]	valid_0's rmse: 1705.65
[212]	valid_0's rmse: 1705.39
[213]	valid_0's rmse: 1705.22
[214]	valid_0's rmse: 1705.15
[215]	valid_0's rmse: 1705.16
[216]	valid_0's rmse: 1704.6
[217]	valid_0's rmse: 1704.27
[218]	valid_0's rmse: 1704.31
[219]	valid_0's rmse: 1704.22
[220]	valid_0's rmse: 1703.61
[221]	valid_0's rmse: 1703.28
[222]	valid_0's rmse: 1703.21
[223]	valid_0's rmse: 1702.95
[224]	valid_0's rmse: 1702.64
[225]	valid_0's rmse: 1702.6
[226]	valid_0's rmse: 1702.43
[227]	valid_0's rmse: 1702.27
[228]	valid_0's rmse: 1701.86
[229]	valid_0's rmse: 1701.78
[230]	valid_0's rmse: 1701.6
[231]	valid_0's rmse: 1701.52
[232]	valid_0's rmse: 1701.44
[233]	valid_0's rmse: 1701.27
[234]	valid_0's rmse: 1701.18
[235]	valid_0's rmse: 1701.17
[236]	valid_0's rmse: 1701.06
[237]	valid_0's rmse: 1700.74
[238]	valid_0's rmse: 1700.59
[239]	valid_0's rmse: 1700.09
[240]	valid_0's rmse: 1700.03
[241]	valid_0's rmse: 1699.69
[242]	valid_0's rmse: 1699.75
[243]	valid_0's rmse: 1699.5
[244]	valid_0's rmse: 1699.4
[245]	valid_0's rmse: 1699.31
[246]	valid_0's rmse: 1699.3
[247]	valid_0's rmse: 1698.88
[248]	valid_0's rmse: 1698.54
[249]	valid_0's rmse: 1698.43
[250]	valid_0's rmse: 1698.32
[251]	valid_0's rmse: 1697.94
[252]	valid_0's rmse: 1697.67
[253]	valid_0's rmse: 1697.17
[254]	valid_0's rmse: 1696.91
[255]	valid_0's rmse: 1696.77
[256]	valid_0's rmse: 1696.65
[257]	valid_0's rmse: 1696.18
[258]	valid_0's rmse: 1695.83
[259]	valid_0's rmse: 1695.83
[260]	valid_0's rmse: 1695.58
[261]	valid_0's rmse: 1695.41
[262]	valid_0's rmse: 1695.13
[263]	valid_0's rmse: 1695.09
[264]	valid_0's rmse: 1694.91
[265]	valid_0's rmse: 1694.84
[266]	valid_0's rmse: 1694.69
[267]	valid_0's rmse: 1694.54
[268]	valid_0's rmse: 1694.26
[269]	valid_0's rmse: 1694.08
[270]	valid_0's rmse: 1694.02
[271]	valid_0's rmse: 1693.84
[272]	valid_0's rmse: 1693.83
[273]	valid_0's rmse: 1693.48
[274]	valid_0's rmse: 1693.41
[275]	valid_0's rmse: 1693.26
[276]	valid_0's rmse: 1693.14
[277]	valid_0's rmse: 1693.06
[278]	valid_0's rmse: 1693.04
[279]	valid_0's rmse: 1693.02
[280]	valid_0's rmse: 1692.86
[281]	valid_0's rmse: 1692.69
[282]	valid_0's rmse: 1692.57
[283]	valid_0's rmse: 1692.18
[284]	valid_0's rmse: 1692.11
[285]	valid_0's rmse: 1691.92
[286]	valid_0's rmse: 1691.87
[287]	valid_0's rmse: 1691.77
[288]	valid_0's rmse: 1691.7
[289]	valid_0's rmse: 1691.62
[290]	valid_0's rmse: 1691.46
[291]	valid_0's rmse: 1691.42
[292]	valid_0's rmse: 1691.43
[293]	valid_0's rmse: 1691.13
[294]	valid_0's rmse: 1691.09
[295]	valid_0's rmse: 1691
[296]	valid_0's rmse: 1690.62
[297]	valid_0's rmse: 1690.56
[298]	valid_0's rmse: 1690.57
[299]	valid_0's rmse: 1690.54
[300]	valid_0's rmse: 1690.26
[301]	valid_0's rmse: 1690.11
[302]	valid_0's rmse: 1689.76
[303]	valid_0's rmse: 1689.71
[304]	valid_0's rmse: 1689.64
[305]	valid_0's rmse: 1689.31
[306]	valid_0's rmse: 1689.27
[307]	valid_0's rmse: 1689.26
[308]	valid_0's rmse: 1689.16
[309]	valid_0's rmse: 1689.09
[310]	valid_0's rmse: 1688.75
[311]	valid_0's rmse: 1688.56
[312]	valid_0's rmse: 1688.48
[313]	valid_0's rmse: 1688.41
[314]	valid_0's rmse: 1688.23
[315]	valid_0's rmse: 1688.15
[316]	valid_0's rmse: 1688.09
[317]	valid_0's rmse: 1687.92
[318]	valid_0's rmse: 1687.8
[319]	valid_0's rmse: 1687.7
[320]	valid_0's rmse: 1687.53
[321]	valid_0's rmse: 1687.5
[322]	valid_0's rmse: 1687.21
[323]	valid_0's rmse: 1687.18
[324]	valid_0's rmse: 1686.95
[325]	valid_0's rmse: 1686.89
[326]	valid_0's rmse: 1686.86
[327]	valid_0's rmse: 1686.8
[328]	valid_0's rmse: 1686.66
[329]	valid_0's rmse: 1686.7
[330]	valid_0's rmse: 1686.74
[331]	valid_0's rmse: 1686.66
[332]	valid_0's rmse: 1686.65
[333]	valid_0's rmse: 1686.47
[334]	valid_0's rmse: 1686.19
[335]	valid_0's rmse: 1686.24
[336]	valid_0's rmse: 1686.17
[337]	valid_0's rmse: 1685.97
[338]	valid_0's rmse: 1685.88
[339]	valid_0's rmse: 1685.87
[340]	valid_0's rmse: 1685.84
[341]	valid_0's rmse: 1685.72
[342]	valid_0's rmse: 1685.64
[343]	valid_0's rmse: 1685.3
[344]	valid_0's rmse: 1685.06
[345]	valid_0's rmse: 1685.01
[346]	valid_0's rmse: 1685.03
[347]	valid_0's rmse: 1684.87
[348]	valid_0's rmse: 1684.73
[349]	valid_0's rmse: 1684.58
[350]	valid_0's rmse: 1684.64
[351]	valid_0's rmse: 1684.47
[352]	valid_0's rmse: 1684.45
[353]	valid_0's rmse: 1684.32
[354]	valid_0's rmse: 1684.3
[355]	valid_0's rmse: 1684.24
[356]	valid_0's rmse: 1684.12
[357]	valid_0's rmse: 1684.16
[358]	valid_0's rmse: 1684.23
[359]	valid_0's rmse: 1683.94
[360]	valid_0's rmse: 1683.91
[361]	valid_0's rmse: 1683.68
[362]	valid_0's rmse: 1683.53
[363]	valid_0's rmse: 1683.49
[364]	valid_0's rmse: 1683.42
[365]	valid_0's rmse: 1683.34
[366]	valid_0's rmse: 1683.22
[367]	valid_0's rmse: 1683.16
[368]	valid_0's rmse: 1683.05
[369]	valid_0's rmse: 1683.04
[370]	valid_0's rmse: 1682.97
[371]	valid_0's rmse: 1682.89
[372]	valid_0's rmse: 1682.84
[373]	valid_0's rmse: 1682.86
[374]	valid_0's rmse: 1682.9
[375]	valid_0's rmse: 1682.95
[376]	valid_0's rmse: 1682.93
[377]	valid_0's rmse: 1683.04
[378]	valid_0's rmse: 1683.03
[379]	valid_0's rmse: 1682.91
[380]	valid_0's rmse: 1682.83
[381]	valid_0's rmse: 1682.77
[382]	valid_0's rmse: 1682.52
[383]	valid_0's rmse: 1682.41
[384]	valid_0's rmse: 1682.27
[385]	valid_0's rmse: 1682.22
[386]	valid_0's rmse: 1681.99
[387]	valid_0's rmse: 1681.96
[388]	valid_0's rmse: 1681.91
[389]	valid_0's rmse: 1681.95
[390]	valid_0's rmse: 1681.98
[391]	valid_0's rmse: 1681.92
[392]	valid_0's rmse: 1681.99
[393]	valid_0's rmse: 1681.86
[394]	valid_0's rmse: 1681.84
[395]	valid_0's rmse: 1681.81
[396]	valid_0's rmse: 1681.77
[397]	valid_0's rmse: 1681.67
[398]	valid_0's rmse: 1681.64
[399]	valid_0's rmse: 1681.61
[400]	valid_0's rmse: 1681.67
[401]	valid_0's rmse: 1681.45
[402]	valid_0's rmse: 1681.32
[403]	valid_0's rmse: 1681.29
[404]	valid_0's rmse: 1681.14
[405]	valid_0's rmse: 1680.83
[406]	valid_0's rmse: 1680.77
[407]	valid_0's rmse: 1680.71
[408]	valid_0's rmse: 1680.65
[409]	valid_0's rmse: 1680.5
[410]	valid_0's rmse: 1680.45
[411]	valid_0's rmse: 1680.28
[412]	valid_0's rmse: 1679.99
[413]	valid_0's rmse: 1679.86
[414]	valid_0's rmse: 1679.65
[415]	valid_0's rmse: 1679.65
[416]	valid_0's rmse: 1679.39
[417]	valid_0's rmse: 1679.15
[418]	valid_0's rmse: 1678.98
[419]	valid_0's rmse: 1678.79
[420]	valid_0's rmse: 1678.81
[421]	valid_0's rmse: 1678.8
[422]	valid_0's rmse: 1678.67
[423]	valid_0's rmse: 1678.58
[424]	valid_0's rmse: 1678.57
[425]	valid_0's rmse: 1678.53
[426]	valid_0's rmse: 1678.39
[427]	valid_0's rmse: 1678.26
[428]	valid_0's rmse: 1678.19
[429]	valid_0's rmse: 1678.03
[430]	valid_0's rmse: 1677.98
[431]	valid_0's rmse: 1677.85
[432]	valid_0's rmse: 1677.79
[433]	valid_0's rmse: 1677.77
[434]	valid_0's rmse: 1677.73
[435]	valid_0's rmse: 1677.65
[436]	valid_0's rmse: 1677.56
[437]	valid_0's rmse: 1677.51
[438]	valid_0's rmse: 1677.27
[439]	valid_0's rmse: 1677.16
[440]	valid_0's rmse: 1676.69
[441]	valid_0's rmse: 1676.55
[442]	valid_0's rmse: 1676.46
[443]	valid_0's rmse: 1676.39
[444]	valid_0's rmse: 1676.32
[445]	valid_0's rmse: 1676.22
[446]	valid_0's rmse: 1676.11
[447]	valid_0's rmse: 1676
[448]	valid_0's rmse: 1675.98
[449]	valid_0's rmse: 1675.88
[450]	valid_0's rmse: 1675.78
[451]	valid_0's rmse: 1675.59
[452]	valid_0's rmse: 1675.53
[453]	valid_0's rmse: 1675.45
[454]	valid_0's rmse: 1675.18
[455]	valid_0's rmse: 1675.18
[456]	valid_0's rmse: 1675.17
[457]	valid_0's rmse: 1675.17
[458]	valid_0's rmse: 1675.2
[459]	valid_0's rmse: 1675.11
[460]	valid_0's rmse: 1675.1
[461]	valid_0's rmse: 1675.18
[462]	valid_0's rmse: 1675.05
[463]	valid_0's rmse: 1675.09
[464]	valid_0's rmse: 1675.15
[465]	valid_0's rmse: 1675.11
[466]	valid_0's rmse: 1675.07
[467]	valid_0's rmse: 1674.97
[468]	valid_0's rmse: 1674.94
[469]	valid_0's rmse: 1674.79
[470]	valid_0's rmse: 1674.78
[471]	valid_0's rmse: 1674.76
[472]	valid_0's rmse: 1674.75
[473]	valid_0's rmse: 1674.75
[474]	valid_0's rmse: 1674.58
[475]	valid_0's rmse: 1674.48
[476]	valid_0's rmse: 1674.35
[477]	valid_0's rmse: 1674.23
[478]	valid_0's rmse: 1674.18
[479]	valid_0's rmse: 1674.21
[480]	valid_0's rmse: 1674.16
[481]	valid_0's rmse: 1674.09
[482]	valid_0's rmse: 1674.08
[483]	valid_0's rmse: 1673.94
[484]	valid_0's rmse: 1673.86
[485]	valid_0's rmse: 1673.81
[486]	valid_0's rmse: 1673.72
[487]	valid_0's rmse: 1673.69
[488]	valid_0's rmse: 1673.55
[489]	valid_0's rmse: 1673.37
[490]	valid_0's rmse: 1673.19
[491]	valid_0's rmse: 1673.04
[492]	valid_0's rmse: 1672.93
[493]	valid_0's rmse: 1672.76
[494]	valid_0's rmse: 1672.63
[495]	valid_0's rmse: 1672.57
[496]	valid_0's rmse: 1672.54
[497]	valid_0's rmse: 1672.53
[498]	valid_0's rmse: 1672.5
[499]	valid_0's rmse: 1672.41
[500]	valid_0's rmse: 1672.36
[501]	valid_0's rmse: 1672.22
[502]	valid_0's rmse: 1672
[503]	valid_0's rmse: 1671.75
[504]	valid_0's rmse: 1671.7
[505]	valid_0's rmse: 1671.67
[506]	valid_0's rmse: 1671.49
[507]	valid_0's rmse: 1671.33
[508]	valid_0's rmse: 1671.15
[509]	valid_0's rmse: 1671.14
[510]	valid_0's rmse: 1671.07
[511]	valid_0's rmse: 1671.05
[512]	valid_0's rmse: 1671.11
[513]	valid_0's rmse: 1671
[514]	valid_0's rmse: 1670.88
[515]	valid_0's rmse: 1670.86
[516]	valid_0's rmse: 1670.67
[517]	valid_0's rmse: 1670.67
[518]	valid_0's rmse: 1670.51
[519]	valid_0's rmse: 1670.47
[520]	valid_0's rmse: 1670.37
[521]	valid_0's rmse: 1670.28
[522]	valid_0's rmse: 1670.18
[523]	valid_0's rmse: 1670.09
[524]	valid_0's rmse: 1670
[525]	valid_0's rmse: 1669.88
[526]	valid_0's rmse: 1669.87
[527]	valid_0's rmse: 1669.83
[528]	valid_0's rmse: 1669.76
[529]	valid_0's rmse: 1669.74
[530]	valid_0's rmse: 1669.79
[531]	valid_0's rmse: 1669.83
[532]	valid_0's rmse: 1669.74
[533]	valid_0's rmse: 1669.65
[534]	valid_0's rmse: 1669.57
[535]	valid_0's rmse: 1669.53
[536]	valid_0's rmse: 1669.55
[537]	valid_0's rmse: 1669.51
[538]	valid_0's rmse: 1669.46
[539]	valid_0's rmse: 1669.45
[540]	valid_0's rmse: 1669.31
[541]	valid_0's rmse: 1669.3
[542]	valid_0's rmse: 1669.26
[543]	valid_0's rmse: 1669.26
[544]	valid_0's rmse: 1669.15
[545]	valid_0's rmse: 1669.17
[546]	valid_0's rmse: 1669.1
[547]	valid_0's rmse: 1669.02
[548]	valid_0's rmse: 1668.99
[549]	valid_0's rmse: 1668.97
[550]	valid_0's rmse: 1668.87
[551]	valid_0's rmse: 1668.88
[552]	valid_0's rmse: 1668.91
[553]	valid_0's rmse: 1668.94
[554]	valid_0's rmse: 1668.67
[555]	valid_0's rmse: 1668.62
[556]	valid_0's rmse: 1668.58
[557]	valid_0's rmse: 1668.57
[558]	valid_0's rmse: 1668.55
[559]	valid_0's rmse: 1668.52
[560]	valid_0's rmse: 1668.44
[561]	valid_0's rmse: 1668.31
[562]	valid_0's rmse: 1668.29
[563]	valid_0's rmse: 1668.27
[564]	valid_0's rmse: 1668.23
[565]	valid_0's rmse: 1668.28
[566]	valid_0's rmse: 1668.31
[567]	valid_0's rmse: 1668.31
[568]	valid_0's rmse: 1668.18
[569]	valid_0's rmse: 1668.14
[570]	valid_0's rmse: 1668.13
[571]	valid_0's rmse: 1668.15
[572]	valid_0's rmse: 1668.13
[573]	valid_0's rmse: 1668.09
[574]	valid_0's rmse: 1667.99
[575]	valid_0's rmse: 1667.95
[576]	valid_0's rmse: 1667.86
[577]	valid_0's rmse: 1667.65
[578]	valid_0's rmse: 1667.6
[579]	valid_0's rmse: 1667.53
[580]	valid_0's rmse: 1667.45
[581]	valid_0's rmse: 1667.4
[582]	valid_0's rmse: 1667.35
[583]	valid_0's rmse: 1667.26
[584]	valid_0's rmse: 1667.29
[585]	valid_0's rmse: 1667.35
[586]	valid_0's rmse: 1667.29
[587]	valid_0's rmse: 1667.29
[588]	valid_0's rmse: 1667.26
[589]	valid_0's rmse: 1667.19
[590]	valid_0's rmse: 1667.13
[591]	valid_0's rmse: 1667.13
[592]	valid_0's rmse: 1666.8
[593]	valid_0's rmse: 1666.77
[594]	valid_0's rmse: 1666.8
[595]	valid_0's rmse: 1666.7
[596]	valid_0's rmse: 1666.67
[597]	valid_0's rmse: 1666.65
[598]	valid_0's rmse: 1666.67
[599]	valid_0's rmse: 1666.56
[600]	valid_0's rmse: 1666.51
[601]	valid_0's rmse: 1666.49
[602]	valid_0's rmse: 1666.52
[603]	valid_0's rmse: 1666.52
[604]	valid_0's rmse: 1666.51
[605]	valid_0's rmse: 1666.48
[606]	valid_0's rmse: 1666.13
[607]	valid_0's rmse: 1666.03
[608]	valid_0's rmse: 1665.84
[609]	valid_0's rmse: 1665.78
[610]	valid_0's rmse: 1665.81
[611]	valid_0's rmse: 1665.64
[612]	valid_0's rmse: 1665.56
[613]	valid_0's rmse: 1665.43
[614]	valid_0's rmse: 1665.39
[615]	valid_0's rmse: 1665.34
[616]	valid_0's rmse: 1665.38
[617]	valid_0's rmse: 1665.31
[618]	valid_0's rmse: 1665.18
[619]	valid_0's rmse: 1665.15
[620]	valid_0's rmse: 1665.01
[621]	valid_0's rmse: 1665.02
[622]	valid_0's rmse: 1665.06
[623]	valid_0's rmse: 1665.04
[624]	valid_0's rmse: 1665.15
[625]	valid_0's rmse: 1665.06
[626]	valid_0's rmse: 1664.99
[627]	valid_0's rmse: 1664.95
[628]	valid_0's rmse: 1664.93
[629]	valid_0's rmse: 1664.91
[630]	valid_0's rmse: 1664.92
[631]	valid_0's rmse: 1664.84
[632]	valid_0's rmse: 1664.78
[633]	valid_0's rmse: 1664.75
[634]	valid_0's rmse: 1664.72
[635]	valid_0's rmse: 1664.64
[636]	valid_0's rmse: 1664.56
[637]	valid_0's rmse: 1664.51
[638]	valid_0's rmse: 1664.47
[639]	valid_0's rmse: 1664.29
[640]	valid_0's rmse: 1664.22
[641]	valid_0's rmse: 1664.27
[642]	valid_0's rmse: 1664.12
[643]	valid_0's rmse: 1663.97
[644]	valid_0's rmse: 1663.95
[645]	valid_0's rmse: 1663.94
[646]	valid_0's rmse: 1663.93
[647]	valid_0's rmse: 1663.96
[648]	valid_0's rmse: 1663.99
[649]	valid_0's rmse: 1664.01
[650]	valid_0's rmse: 1663.87
[651]	valid_0's rmse: 1663.83
[652]	valid_0's rmse: 1663.7
[653]	valid_0's rmse: 1663.65
[654]	valid_0's rmse: 1663.69
[655]	valid_0's rmse: 1663.65
[656]	valid_0's rmse: 1663.6
[657]	valid_0's rmse: 1663.64
[658]	valid_0's rmse: 1663.67
[659]	valid_0's rmse: 1663.64
[660]	valid_0's rmse: 1663.48
[661]	valid_0's rmse: 1663.48
[662]	valid_0's rmse: 1663.41
[663]	valid_0's rmse: 1663.42
[664]	valid_0's rmse: 1663.31
[665]	valid_0's rmse: 1663.23
[666]	valid_0's rmse: 1663.2
[667]	valid_0's rmse: 1663.16
[668]	valid_0's rmse: 1663.27
[669]	valid_0's rmse: 1663.24
[670]	valid_0's rmse: 1663.11
[671]	valid_0's rmse: 1663.09

LGBMRegressor(metric='rmse', num_iterations=1000, vebose=1)

In [30]:
# %%

pred_train = model.predict(features_train)
pred_valid = model.predict(features_valid)
pred_test = model.predict(features_test)

In [31]:
# %%
print("Train RMSE:", rmse(target_train, pred_train).round(5))
print("Valid RMSE:", rmse(target_valid, pred_valid).round(5))
print("Test RMSE: ", rmse(target_test, pred_test).round(5))

Train RMSE: 1410.16135
Valid RMSE: 1650.98246
Test RMSE:  1643.3866

In [32]:
# %%

import lightgbm as lgb

model = lgb.LGBMRegressor(num_iterations=1000, vebose=1, metric='rmse')
model.fit(features_train, target_train, 
          eval_set=(features_valid, target_valid))

[LightGBM] [Warning] Unknown parameter: vebose
[1]	valid_0's rmse: 4268.81
[2]	valid_0's rmse: 3988.72
[3]	valid_0's rmse: 3745.28
[4]	valid_0's rmse: 3533.96
[5]	valid_0's rmse: 3344.79
[6]	valid_0's rmse: 3180.15
[7]	valid_0's rmse: 3038.53
[8]	valid_0's rmse: 2913.76
[9]	valid_0's rmse: 2800.89
[10]	valid_0's rmse: 2703.65
[11]	valid_0's rmse: 2623.15
[12]	valid_0's rmse: 2548.09
[13]	valid_0's rmse: 2484.49
[14]	valid_0's rmse: 2428.51
[15]	valid_0's rmse: 2376.84
[16]	valid_0's rmse: 2330.6
[17]	valid_0's rmse: 2291.97
[18]	valid_0's rmse: 2256.88
[19]	valid_0's rmse: 2225.96
[20]	valid_0's rmse: 2197.94

/Users/juliokorleone/anaconda3/lib/python3.10/site-packages/lightgbm/engine.py:177: UserWarning: Found `num_iterations` in params. Will use it instead of argument
  _log_warning(f"Found `{alias}` in params. Will use it instead of argument")

[21]	valid_0's rmse: 2172.21
[22]	valid_0's rmse: 2146.89
[23]	valid_0's rmse: 2125.14
[24]	valid_0's rmse: 2105.92
[25]	valid_0's rmse: 2085.68
[26]	valid_0's rmse: 2069.76
[27]	valid_0's rmse: 2055.27
[28]	valid_0's rmse: 2041.37
[29]	valid_0's rmse: 2030.06
[30]	valid_0's rmse: 2019.88
[31]	valid_0's rmse: 2009.93
[32]	valid_0's rmse: 1999.63
[33]	valid_0's rmse: 1990.62
[34]	valid_0's rmse: 1984.02
[35]	valid_0's rmse: 1974.87
[36]	valid_0's rmse: 1967.7
[37]	valid_0's rmse: 1959.75
[38]	valid_0's rmse: 1952.77
[39]	valid_0's rmse: 1945.53
[40]	valid_0's rmse: 1940.22
[41]	valid_0's rmse: 1935.15
[42]	valid_0's rmse: 1930.31
[43]	valid_0's rmse: 1925.69
[44]	valid_0's rmse: 1920.23
[45]	valid_0's rmse: 1914.48
[46]	valid_0's rmse: 1910.76
[47]	valid_0's rmse: 1907.91
[48]	valid_0's rmse: 1903.88
[49]	valid_0's rmse: 1901.23
[50]	valid_0's rmse: 1898.23
[51]	valid_0's rmse: 1895.32
[52]	valid_0's rmse: 1890.67
[53]	valid_0's rmse: 1886.49
[54]	valid_0's rmse: 1884.32
[55]	valid_0's rmse: 1882.24
[56]	valid_0's rmse: 1878.8
[57]	valid_0's rmse: 1876.24
[58]	valid_0's rmse: 1874.59
[59]	valid_0's rmse: 1872.04
[60]	valid_0's rmse: 1869.56
[61]	valid_0's rmse: 1867.07
[62]	valid_0's rmse: 1865.36
[63]	valid_0's rmse: 1863.55
[64]	valid_0's rmse: 1860.67
[65]	valid_0's rmse: 1858.53
[66]	valid_0's rmse: 1857.16
[67]	valid_0's rmse: 1855.45
[68]	valid_0's rmse: 1854.57
[69]	valid_0's rmse: 1852.84
[70]	valid_0's rmse: 1851.13
[71]	valid_0's rmse: 1849.95
[72]	valid_0's rmse: 1847.76
[73]	valid_0's rmse: 1845.9
[74]	valid_0's rmse: 1843.51
[75]	valid_0's rmse: 1841.83
[76]	valid_0's rmse: 1840.85
[77]	valid_0's rmse: 1839.6
[78]	valid_0's rmse: 1838
[79]	valid_0's rmse: 1836.31
[80]	valid_0's rmse: 1835.64
[81]	valid_0's rmse: 1834.66
[82]	valid_0's rmse: 1833.94
[83]	valid_0's rmse: 1833.22
[84]	valid_0's rmse: 1831.78
[85]	valid_0's rmse: 1830.17
[86]	valid_0's rmse: 1829.24
[87]	valid_0's rmse: 1827.56
[88]	valid_0's rmse: 1826.05
[89]	valid_0's rmse: 1825.47
[90]	valid_0's rmse: 1824.95
[91]	valid_0's rmse: 1824.73
[92]	valid_0's rmse: 1823.32
[93]	valid_0's rmse: 1821.98
[94]	valid_0's rmse: 1821.06
[95]	valid_0's rmse: 1820.52
[96]	valid_0's rmse: 1819.76
[97]	valid_0's rmse: 1818.75
[98]	valid_0's rmse: 1818.16
[99]	valid_0's rmse: 1817.49
[100]	valid_0's rmse: 1817.17
[101]	valid_0's rmse: 1816.87
[102]	valid_0's rmse: 1816.05
[103]	valid_0's rmse: 1814.7
[104]	valid_0's rmse: 1813.73
[105]	valid_0's rmse: 1813.4
[106]	valid_0's rmse: 1812.8
[107]	valid_0's rmse: 1812.1
[108]	valid_0's rmse: 1811.6
[109]	valid_0's rmse: 1810.3
[110]	valid_0's rmse: 1809.89
[111]	valid_0's rmse: 1808.53
[112]	valid_0's rmse: 1807.53
[113]	valid_0's rmse: 1806.29
[114]	valid_0's rmse: 1805.48
[115]	valid_0's rmse: 1805.1
[116]	valid_0's rmse: 1804.19
[117]	valid_0's rmse: 1803.81
[118]	valid_0's rmse: 1803.18
[119]	valid_0's rmse: 1801.77
[120]	valid_0's rmse: 1800.9
[121]	valid_0's rmse: 1799.68
[122]	valid_0's rmse: 1799.28
[123]	valid_0's rmse: 1798.23
[124]	valid_0's rmse: 1797.86
[125]	valid_0's rmse: 1796.55
[126]	valid_0's rmse: 1795.92
[127]	valid_0's rmse: 1795.29
[128]	valid_0's rmse: 1794.2
[129]	valid_0's rmse: 1793.35
[130]	valid_0's rmse: 1792.47
[131]	valid_0's rmse: 1791.46
[132]	valid_0's rmse: 1790.82
[133]	valid_0's rmse: 1789.59
[134]	valid_0's rmse: 1789.06
[135]	valid_0's rmse: 1788.18
[136]	valid_0's rmse: 1787.21
[137]	valid_0's rmse: 1786.72
[138]	valid_0's rmse: 1785.67
[139]	valid_0's rmse: 1784.85
[140]	valid_0's rmse: 1784.6
[141]	valid_0's rmse: 1784.11
[142]	valid_0's rmse: 1783.57
[143]	valid_0's rmse: 1782.81
[144]	valid_0's rmse: 1782.25
[145]	valid_0's rmse: 1782.05
[146]	valid_0's rmse: 1781.28
[147]	valid_0's rmse: 1780.89
[148]	valid_0's rmse: 1780.43
[149]	valid_0's rmse: 1779.71
[150]	valid_0's rmse: 1779.15
[151]	valid_0's rmse: 1778.52
[152]	valid_0's rmse: 1778.08
[153]	valid_0's rmse: 1777.35
[154]	valid_0's rmse: 1776.6
[155]	valid_0's rmse: 1775.77
[156]	valid_0's rmse: 1775.27
[157]	valid_0's rmse: 1774.64
[158]	valid_0's rmse: 1774.37
[159]	valid_0's rmse: 1773.78
[160]	valid_0's rmse: 1773.8
[161]	valid_0's rmse: 1773.55
[162]	valid_0's rmse: 1773.27
[163]	valid_0's rmse: 1772.7
[164]	valid_0's rmse: 1771.93
[165]	valid_0's rmse: 1771.33
[166]	valid_0's rmse: 1770.6
[167]	valid_0's rmse: 1770.09
[168]	valid_0's rmse: 1769.67
[169]	valid_0's rmse: 1769.33
[170]	valid_0's rmse: 1768.82
[171]	valid_0's rmse: 1768.46
[172]	valid_0's rmse: 1767.79
[173]	valid_0's rmse: 1767.16
[174]	valid_0's rmse: 1766.77
[175]	valid_0's rmse: 1766.55
[176]	valid_0's rmse: 1765.85
[177]	valid_0's rmse: 1765.43
[178]	valid_0's rmse: 1764.94
[179]	valid_0's rmse: 1764.37
[180]	valid_0's rmse: 1764.25
[181]	valid_0's rmse: 1763.48
[182]	valid_0's rmse: 1763.25
[183]	valid_0's rmse: 1762.76
[184]	valid_0's rmse: 1762.27
[185]	valid_0's rmse: 1761.89
[186]	valid_0's rmse: 1761.29
[187]	valid_0's rmse: 1760.67
[188]	valid_0's rmse: 1760.55
[189]	valid_0's rmse: 1760.33
[190]	valid_0's rmse: 1760.04
[191]	valid_0's rmse: 1759.9
[192]	valid_0's rmse: 1759.49
[193]	valid_0's rmse: 1759.22
[194]	valid_0's rmse: 1759.04
[195]	valid_0's rmse: 1758.86
[196]	valid_0's rmse: 1758.62
[197]	valid_0's rmse: 1758.24
[198]	valid_0's rmse: 1757.9
[199]	valid_0's rmse: 1757.89
[200]	valid_0's rmse: 1757.82
[201]	valid_0's rmse: 1757.23
[202]	valid_0's rmse: 1756.46
[203]	valid_0's rmse: 1755.97
[204]	valid_0's rmse: 1755.53
[205]	valid_0's rmse: 1755.35
[206]	valid_0's rmse: 1755.3
[207]	valid_0's rmse: 1754.78
[208]	valid_0's rmse: 1754.65
[209]	valid_0's rmse: 1754.09
[210]	valid_0's rmse: 1753.93
[211]	valid_0's rmse: 1753.63
[212]	valid_0's rmse: 1753.26
[213]	valid_0's rmse: 1752.94
[214]	valid_0's rmse: 1752.49
[215]	valid_0's rmse: 1752.32
[216]	valid_0's rmse: 1751.74
[217]	valid_0's rmse: 1751.3
[218]	valid_0's rmse: 1750.71
[219]	valid_0's rmse: 1750.75
[220]	valid_0's rmse: 1750.57
[221]	valid_0's rmse: 1750.57
[222]	valid_0's rmse: 1750.3
[223]	valid_0's rmse: 1749.88
[224]	valid_0's rmse: 1749.47
[225]	valid_0's rmse: 1749.24
[226]	valid_0's rmse: 1748.85
[227]	valid_0's rmse: 1748.72
[228]	valid_0's rmse: 1748.5
[229]	valid_0's rmse: 1747.96
[230]	valid_0's rmse: 1747.56
[231]	valid_0's rmse: 1747.2
[232]	valid_0's rmse: 1747.14
[233]	valid_0's rmse: 1746.89
[234]	valid_0's rmse: 1746.48
[235]	valid_0's rmse: 1746.48
[236]	valid_0's rmse: 1746.29
[237]	valid_0's rmse: 1746.07
[238]	valid_0's rmse: 1745.85
[239]	valid_0's rmse: 1745.52
[240]	valid_0's rmse: 1745.18
[241]	valid_0's rmse: 1744.75
[242]	valid_0's rmse: 1744.62
[243]	valid_0's rmse: 1744.45
[244]	valid_0's rmse: 1744
[245]	valid_0's rmse: 1743.99
[246]	valid_0's rmse: 1743.82
[247]	valid_0's rmse: 1743.45
[248]	valid_0's rmse: 1743.13
[249]	valid_0's rmse: 1742.9
[250]	valid_0's rmse: 1742.61
[251]	valid_0's rmse: 1742.21
[252]	valid_0's rmse: 1742.19
[253]	valid_0's rmse: 1741.98
[254]	valid_0's rmse: 1741.92
[255]	valid_0's rmse: 1741.68
[256]	valid_0's rmse: 1741.29
[257]	valid_0's rmse: 1740.95
[258]	valid_0's rmse: 1740.85
[259]	valid_0's rmse: 1740.59
[260]	valid_0's rmse: 1740.43
[261]	valid_0's rmse: 1739.83
[262]	valid_0's rmse: 1739.43
[263]	valid_0's rmse: 1739.34
[264]	valid_0's rmse: 1738.71
[265]	valid_0's rmse: 1738.65
[266]	valid_0's rmse: 1738.72
[267]	valid_0's rmse: 1738.64
[268]	valid_0's rmse: 1738.3
[269]	valid_0's rmse: 1738.19
[270]	valid_0's rmse: 1737.77
[271]	valid_0's rmse: 1737.73
[272]	valid_0's rmse: 1737.69
[273]	valid_0's rmse: 1737.68
[274]	valid_0's rmse: 1737.6
[275]	valid_0's rmse: 1737.06
[276]	valid_0's rmse: 1737
[277]	valid_0's rmse: 1736.64
[278]	valid_0's rmse: 1736.54
[279]	valid_0's rmse: 1736.3
[280]	valid_0's rmse: 1735.99
[281]	valid_0's rmse: 1735.59
[282]	valid_0's rmse: 1735.45
[283]	valid_0's rmse: 1735.11
[284]	valid_0's rmse: 1734.94
[285]	valid_0's rmse: 1734.57
[286]	valid_0's rmse: 1734.21
[287]	valid_0's rmse: 1733.82
[288]	valid_0's rmse: 1733.66
[289]	valid_0's rmse: 1733.49
[290]	valid_0's rmse: 1733.31
[291]	valid_0's rmse: 1732.97
[292]	valid_0's rmse: 1732.76
[293]	valid_0's rmse: 1732.68
[294]	valid_0's rmse: 1732.54
[295]	valid_0's rmse: 1732.08
[296]	valid_0's rmse: 1731.86
[297]	valid_0's rmse: 1731.49
[298]	valid_0's rmse: 1731.35
[299]	valid_0's rmse: 1731.23
[300]	valid_0's rmse: 1730.98
[301]	valid_0's rmse: 1730.86
[302]	valid_0's rmse: 1730.91
[303]	valid_0's rmse: 1730.76
[304]	valid_0's rmse: 1730.6
[305]	valid_0's rmse: 1730.4
[306]	valid_0's rmse: 1730.18
[307]	valid_0's rmse: 1729.97
[308]	valid_0's rmse: 1729.85
[309]	valid_0's rmse: 1729.48
[310]	valid_0's rmse: 1729.15
[311]	valid_0's rmse: 1728.73
[312]	valid_0's rmse: 1728.68
[313]	valid_0's rmse: 1728.45
[314]	valid_0's rmse: 1728.38
[315]	valid_0's rmse: 1728.26
[316]	valid_0's rmse: 1727.92
[317]	valid_0's rmse: 1727.77
[318]	valid_0's rmse: 1727.64
[319]	valid_0's rmse: 1727.68
[320]	valid_0's rmse: 1727.31
[321]	valid_0's rmse: 1727.03
[322]	valid_0's rmse: 1726.88
[323]	valid_0's rmse: 1726.7
[324]	valid_0's rmse: 1726.6
[325]	valid_0's rmse: 1726.54
[326]	valid_0's rmse: 1726.36
[327]	valid_0's rmse: 1726.25
[328]	valid_0's rmse: 1726.14
[329]	valid_0's rmse: 1726.01
[330]	valid_0's rmse: 1726.03
[331]	valid_0's rmse: 1725.95
[332]	valid_0's rmse: 1725.72
[333]	valid_0's rmse: 1725.41
[334]	valid_0's rmse: 1725
[335]	valid_0's rmse: 1725
[336]	valid_0's rmse: 1724.71
[337]	valid_0's rmse: 1724.43
[338]	valid_0's rmse: 1724.26
[339]	valid_0's rmse: 1724.17
[340]	valid_0's rmse: 1723.88
[341]	valid_0's rmse: 1723.87
[342]	valid_0's rmse: 1723.54
[343]	valid_0's rmse: 1723.36
[344]	valid_0's rmse: 1723.17
[345]	valid_0's rmse: 1723.16
[346]	valid_0's rmse: 1722.84
[347]	valid_0's rmse: 1722.65
[348]	valid_0's rmse: 1722.56
[349]	valid_0's rmse: 1722.52
[350]	valid_0's rmse: 1722.41
[351]	valid_0's rmse: 1722.18
[352]	valid_0's rmse: 1722.13
[353]	valid_0's rmse: 1722.1
[354]	valid_0's rmse: 1721.8
[355]	valid_0's rmse: 1721.68
[356]	valid_0's rmse: 1721.47
[357]	valid_0's rmse: 1721.38
[358]	valid_0's rmse: 1721.1
[359]	valid_0's rmse: 1721.02
[360]	valid_0's rmse: 1720.95
[361]	valid_0's rmse: 1720.89
[362]	valid_0's rmse: 1720.85
[363]	valid_0's rmse: 1720.74
[364]	valid_0's rmse: 1720.57
[365]	valid_0's rmse: 1720.56
[366]	valid_0's rmse: 1720.59
[367]	valid_0's rmse: 1720.52
[368]	valid_0's rmse: 1720.38
[369]	valid_0's rmse: 1720.27
[370]	valid_0's rmse: 1720.19
[371]	valid_0's rmse: 1720.05
[372]	valid_0's rmse: 1720
[373]	valid_0's rmse: 1719.99
[374]	valid_0's rmse: 1719.87
[375]	valid_0's rmse: 1719.78
[376]	valid_0's rmse: 1719.49
[377]	valid_0's rmse: 1719.28
[378]	valid_0's rmse: 1719.12
[379]	valid_0's rmse: 1719.09
[380]	valid_0's rmse: 1719.11
[381]	valid_0's rmse: 1719.01
[382]	valid_0's rmse: 1718.65
[383]	valid_0's rmse: 1718.57
[384]	valid_0's rmse: 1718.54
[385]	valid_0's rmse: 1718.29
[386]	valid_0's rmse: 1718.14
[387]	valid_0's rmse: 1718
[388]	valid_0's rmse: 1717.75
[389]	valid_0's rmse: 1717.81
[390]	valid_0's rmse: 1717.64
[391]	valid_0's rmse: 1717.47
[392]	valid_0's rmse: 1717.1
[393]	valid_0's rmse: 1716.71
[394]	valid_0's rmse: 1716.52
[395]	valid_0's rmse: 1716.37
[396]	valid_0's rmse: 1716.39
[397]	valid_0's rmse: 1716.34
[398]	valid_0's rmse: 1716.18
[399]	valid_0's rmse: 1716.04
[400]	valid_0's rmse: 1715.98
[401]	valid_0's rmse: 1715.6
[402]	valid_0's rmse: 1715.44
[403]	valid_0's rmse: 1715.33
[404]	valid_0's rmse: 1715.03
[405]	valid_0's rmse: 1714.84
[406]	valid_0's rmse: 1714.8
[407]	valid_0's rmse: 1714.6
[408]	valid_0's rmse: 1714.41
[409]	valid_0's rmse: 1714.33
[410]	valid_0's rmse: 1714.31
[411]	valid_0's rmse: 1714.01
[412]	valid_0's rmse: 1713.77
[413]	valid_0's rmse: 1713.43
[414]	valid_0's rmse: 1713.31
[415]	valid_0's rmse: 1713.14
[416]	valid_0's rmse: 1713.08
[417]	valid_0's rmse: 1713.08
[418]	valid_0's rmse: 1712.91
[419]	valid_0's rmse: 1712.77
[420]	valid_0's rmse: 1712.74
[421]	valid_0's rmse: 1712.49
[422]	valid_0's rmse: 1712.13
[423]	valid_0's rmse: 1712.05
[424]	valid_0's rmse: 1711.7
[425]	valid_0's rmse: 1711.54
[426]	valid_0's rmse: 1711.53
[427]	valid_0's rmse: 1711.4
[428]	valid_0's rmse: 1711.2
[429]	valid_0's rmse: 1710.98
[430]	valid_0's rmse: 1710.75
[431]	valid_0's rmse: 1710.65
[432]	valid_0's rmse: 1710.54
[433]	valid_0's rmse: 1710.45
[434]	valid_0's rmse: 1710.43
[435]	valid_0's rmse: 1710.25
[436]	valid_0's rmse: 1710.27
[437]	valid_0's rmse: 1710.19
[438]	valid_0's rmse: 1710.12
[439]	valid_0's rmse: 1709.97
[440]	valid_0's rmse: 1709.76
[441]	valid_0's rmse: 1709.57
[442]	valid_0's rmse: 1709.55
[443]	valid_0's rmse: 1709.34
[444]	valid_0's rmse: 1709.27
[445]	valid_0's rmse: 1709.06
[446]	valid_0's rmse: 1708.87
[447]	valid_0's rmse: 1708.77
[448]	valid_0's rmse: 1708.6
[449]	valid_0's rmse: 1708.53
[450]	valid_0's rmse: 1708.34
[451]	valid_0's rmse: 1708.26
[452]	valid_0's rmse: 1708.21
[453]	valid_0's rmse: 1708.08
[454]	valid_0's rmse: 1707.89
[455]	valid_0's rmse: 1707.92
[456]	valid_0's rmse: 1707.72
[457]	valid_0's rmse: 1707.54
[458]	valid_0's rmse: 1707.47
[459]	valid_0's rmse: 1707.33
[460]	valid_0's rmse: 1707.17
[461]	valid_0's rmse: 1706.95
[462]	valid_0's rmse: 1706.82
[463]	valid_0's rmse: 1706.84
[464]	valid_0's rmse: 1706.77
[465]	valid_0's rmse: 1706.8
[466]	valid_0's rmse: 1706.72
[467]	valid_0's rmse: 1706.57
[468]	valid_0's rmse: 1706.6
[469]	valid_0's rmse: 1706.44
[470]	valid_0's rmse: 1706.35
[471]	valid_0's rmse: 1706.52
[472]	valid_0's rmse: 1706.37
[473]	valid_0's rmse: 1706.3
[474]	valid_0's rmse: 1706.21
[475]	valid_0's rmse: 1706.2
[476]	valid_0's rmse: 1706.07
[477]	valid_0's rmse: 1705.81
[478]	valid_0's rmse: 1705.78
[479]	valid_0's rmse: 1705.69
[480]	valid_0's rmse: 1705.49
[481]	valid_0's rmse: 1705.35
[482]	valid_0's rmse: 1705.35
[483]	valid_0's rmse: 1705.29
[484]	valid_0's rmse: 1705.25
[485]	valid_0's rmse: 1705.29
[486]	valid_0's rmse: 1705.16
[487]	valid_0's rmse: 1704.96
[488]	valid_0's rmse: 1704.88
[489]	valid_0's rmse: 1704.78
[490]	valid_0's rmse: 1704.69
[491]	valid_0's rmse: 1704.53
[492]	valid_0's rmse: 1704.54
[493]	valid_0's rmse: 1704.49
[494]	valid_0's rmse: 1704.34
[495]	valid_0's rmse: 1704.27
[496]	valid_0's rmse: 1704.32
[497]	valid_0's rmse: 1704.31
[498]	valid_0's rmse: 1704.29
[499]	valid_0's rmse: 1704.26
[500]	valid_0's rmse: 1704.17
[501]	valid_0's rmse: 1704.06
[502]	valid_0's rmse: 1703.87
[503]	valid_0's rmse: 1703.86
[504]	valid_0's rmse: 1703.78
[505]	valid_0's rmse: 1703.54
[506]	valid_0's rmse: 1703.54
[507]	valid_0's rmse: 1703.48
[508]	valid_0's rmse: 1703.21
[509]	valid_0's rmse: 1703.15
[510]	valid_0's rmse: 1702.93
[511]	valid_0's rmse: 1702.92
[512]	valid_0's rmse: 1702.69
[513]	valid_0's rmse: 1702.47
[514]	valid_0's rmse: 1702.5
[515]	valid_0's rmse: 1702.38
[516]	valid_0's rmse: 1702.14
[517]	valid_0's rmse: 1701.95
[518]	valid_0's rmse: 1701.81
[519]	valid_0's rmse: 1701.77
[520]	valid_0's rmse: 1701.53
[521]	valid_0's rmse: 1701.41
[522]	valid_0's rmse: 1701.33
[523]	valid_0's rmse: 1701.3
[524]	valid_0's rmse: 1701.19
[525]	valid_0's rmse: 1701.08
[526]	valid_0's rmse: 1701.02
[527]	valid_0's rmse: 1700.98
[528]	valid_0's rmse: 1700.92
[529]	valid_0's rmse: 1700.75
[530]	valid_0's rmse: 1700.67
[531]	valid_0's rmse: 1700.55
[532]	valid_0's rmse: 1700.48
[533]	valid_0's rmse: 1700.43
[534]	valid_0's rmse: 1700.22
[535]	valid_0's rmse: 1700.13
[536]	valid_0's rmse: 1699.92
[537]	valid_0's rmse: 1699.64
[538]	valid_0's rmse: 1699.65
[539]	valid_0's rmse: 1699.5
[540]	valid_0's rmse: 1699.42
[541]	valid_0's rmse: 1699.32
[542]	valid_0's rmse: 1699.25
[543]	valid_0's rmse: 1699.18
[544]	valid_0's rmse: 1699.24
[545]	valid_0's rmse: 1699.15
[546]	valid_0's rmse: 1699.13
[547]	valid_0's rmse: 1698.9
[548]	valid_0's rmse: 1698.86
[549]	valid_0's rmse: 1698.65
[550]	valid_0's rmse: 1698.51
[551]	valid_0's rmse: 1698.4
[552]	valid_0's rmse: 1698.23
[553]	valid_0's rmse: 1698.1
[554]	valid_0's rmse: 1698
[555]	valid_0's rmse: 1697.98
[556]	valid_0's rmse: 1697.85
[557]	valid_0's rmse: 1697.75
[558]	valid_0's rmse: 1697.71
[559]	valid_0's rmse: 1697.65
[560]	valid_0's rmse: 1697.47
[561]	valid_0's rmse: 1697.34
[562]	valid_0's rmse: 1697.29
[563]	valid_0's rmse: 1697.17
[564]	valid_0's rmse: 1697.14
[565]	valid_0's rmse: 1697.16
[566]	valid_0's rmse: 1697.05
[567]	valid_0's rmse: 1696.82
[568]	valid_0's rmse: 1696.72
[569]	valid_0's rmse: 1696.66
[570]	valid_0's rmse: 1696.66
[571]	valid_0's rmse: 1696.62
[572]	valid_0's rmse: 1696.53
[573]	valid_0's rmse: 1696.46
[574]	valid_0's rmse: 1696.48
[575]	valid_0's rmse: 1696.48
[576]	valid_0's rmse: 1696.31
[577]	valid_0's rmse: 1696.32
[578]	valid_0's rmse: 1696.27
[579]	valid_0's rmse: 1696.33
[580]	valid_0's rmse: 1696.29
[581]	valid_0's rmse: 1696.22
[582]	valid_0's rmse: 1696.35
[583]	valid_0's rmse: 1696.38
[584]	valid_0's rmse: 1696.26
[585]	valid_0's rmse: 1696.14
[586]	valid_0's rmse: 1696.09
[587]	valid_0's rmse: 1695.94
[588]	valid_0's rmse: 1695.95
[589]	valid_0's rmse: 1695.77
[590]	valid_0's rmse: 1695.74
[591]	valid_0's rmse: 1695.72
[592]	valid_0's rmse: 1695.66
[593]	valid_0's rmse: 1695.56
[594]	valid_0's rmse: 1695.39
[595]	valid_0's rmse: 1695.29
[596]	valid_0's rmse: 1695.11
[597]	valid_0's rmse: 1695.12
[598]	valid_0's rmse: 1695.03
[599]	valid_0's rmse: 1694.96
[600]	valid_0's rmse: 1694.92
[601]	valid_0's rmse: 1694.83
[602]	valid_0's rmse: 1694.87
[603]	valid_0's rmse: 1694.68
[604]	valid_0's rmse: 1694.6
[605]	valid_0's rmse: 1694.45
[606]	valid_0's rmse: 1694.43
[607]	valid_0's rmse: 1694.49
[608]	valid_0's rmse: 1694.53
[609]	valid_0's rmse: 1694.55
[610]	valid_0's rmse: 1694.44
[611]	valid_0's rmse: 1694.41
[612]	valid_0's rmse: 1694.35
[613]	valid_0's rmse: 1694.24
[614]	valid_0's rmse: 1694.17
[615]	valid_0's rmse: 1694.07
[616]	valid_0's rmse: 1694.12
[617]	valid_0's rmse: 1694.15
[618]	valid_0's rmse: 1693.9
[619]	valid_0's rmse: 1693.9
[620]	valid_0's rmse: 1693.89
[621]	valid_0's rmse: 1693.86
[622]	valid_0's rmse: 1693.67
[623]	valid_0's rmse: 1693.49
[624]	valid_0's rmse: 1693.46
[625]	valid_0's rmse: 1693.37
[626]	valid_0's rmse: 1693.32
[627]	valid_0's rmse: 1693.33
[628]	valid_0's rmse: 1693.09
[629]	valid_0's rmse: 1693.01
[630]	valid_0's rmse: 1692.84
[631]	valid_0's rmse: 1692.8
[632]	valid_0's rmse: 1692.61
[633]	valid_0's rmse: 1692.62
[634]	valid_0's rmse: 1692.66
[635]	valid_0's rmse: 1692.46
[636]	valid_0's rmse: 1692.34
[637]	valid_0's rmse: 1692.32
[638]	valid_0's rmse: 1692.4
[639]	valid_0's rmse: 1692.37
[640]	valid_0's rmse: 1692.31
[641]	valid_0's rmse: 1692.23
[642]	valid_0's rmse: 1692.19
[643]	valid_0's rmse: 1692.14
[644]	valid_0's rmse: 1692.07
[645]	valid_0's rmse: 1692.02
[646]	valid_0's rmse: 1691.98
[647]	valid_0's rmse: 1691.87
[648]	valid_0's rmse: 1691.82
[649]	valid_0's rmse: 1691.78
[650]	valid_0's rmse: 1691.69
[651]	valid_0's rmse: 1691.61
[652]	valid_0's rmse: 1691.38
[653]	valid_0's rmse: 1691.27
[654]	valid_0's rmse: 1691.19
[655]	valid_0's rmse: 1691.03
[656]	valid_0's rmse: 1691
[657]	valid_0's rmse: 1690.98
[658]	valid_0's rmse: 1690.85
[659]	valid_0's rmse: 1690.77
[660]	valid_0's rmse: 1690.65
[661]	valid_0's rmse: 1690.55
[662]	valid_0's rmse: 1690.53
[663]	valid_0's rmse: 1690.44
[664]	valid_0's rmse: 1690.49
[665]	valid_0's rmse: 1690.43
[666]	valid_0's rmse: 1690.38
[667]	valid_0's rmse: 1690.27
[668]	valid_0's rmse: 1690.15
[669]	valid_0's rmse: 1690.11
[670]	valid_0's rmse: 1690.01
[671]	valid_0's rmse: 1690.07
[672]	valid_0's rmse: 1690.02
[673]	valid_0's rmse: 1689.96
[674]	valid_0's rmse: 1689.95
[675]	valid_0's rmse: 1689.94
[676]	valid_0's rmse: 1689.93
[677]	valid_0's rmse: 1689.86
[678]	valid_0's rmse: 1689.8
[679]	valid_0's rmse: 1689.8
[680]	valid_0's rmse: 1689.61
[681]	valid_0's rmse: 1689.53
[682]	valid_0's rmse: 1689.5
[683]	valid_0's rmse: 1689.48
[684]	valid_0's rmse: 1689.46
[685]	valid_0's rmse: 1689.4
[686]	valid_0's rmse: 1689.36
[687]	valid_0's rmse: 1689.36
[688]	valid_0's rmse: 1689.23
[689]	valid_0's rmse: 1689.13
[690]	valid_0's rmse: 1689.18
[691]	valid_0's rmse: 1689.1
[692]	valid_0's rmse: 1689.05

LGBMRegressor(metric='rmse', num_iterations=1000, vebose=1)

In [33]:
# %%

pred_train = model.predict(features_train)
pred_valid = model.predict(features_valid)
pred_test = model.predict(features_test)

In [34]:
# %%
print("Train RMSE:", rmse(target_train, pred_train).round(5))
print("Valid RMSE:", rmse(target_valid, pred_valid).round(5))
print("Test RMSE: ", rmse(target_test, pred_test).round(5))

Train RMSE: 1460.69366
Valid RMSE: 1674.35245
Test RMSE:  1657.71951

 **Gradient boosting CatBoost**

In [40]:
# %%

from catboost import CatBoostRegressor

model = CatBoostRegressor(iterations=1000,
                          learning_rate=0.1,
                          #cat_features=data[categorical_features].dropna(), # TODO FIXME Invalid type for cat_feature[non-default value idx=0,feature_idx=0]=4.0 : cat_features must be integer or string, real number values and NaN values should be converted to string.
                          metric_period=50)
model.fit(features_train, target_train, 
          eval_set=(features_valid, target_valid))

0:	learn: 4303.6641569	test: 4301.7128896	best: 4301.7128896 (0)	total: 7.38ms	remaining: 7.37s
50:	learn: 2038.0178504	test: 2040.6427778	best: 2040.6427778 (50)	total: 310ms	remaining: 5.78s
100:	learn: 1916.1013000	test: 1924.7826614	best: 1924.7826614 (100)	total: 565ms	remaining: 5.03s
150:	learn: 1861.0469932	test: 1875.5131021	best: 1875.5131021 (150)	total: 824ms	remaining: 4.63s
200:	learn: 1825.3551799	test: 1846.3659885	best: 1846.3659885 (200)	total: 1.09s	remaining: 4.33s
250:	learn: 1798.6495174	test: 1824.8524135	best: 1824.8524135 (250)	total: 1.34s	remaining: 4s
300:	learn: 1778.0522977	test: 1809.5490852	best: 1809.5490852 (300)	total: 1.58s	remaining: 3.67s
350:	learn: 1759.2884167	test: 1795.8827617	best: 1795.8827617 (350)	total: 1.82s	remaining: 3.36s
400:	learn: 1743.8840102	test: 1785.3495521	best: 1785.3495521 (400)	total: 2.06s	remaining: 3.08s
450:	learn: 1730.0319854	test: 1775.2968687	best: 1775.2968687 (450)	total: 2.3s	remaining: 2.8s
500:	learn: 1717.6155975	test: 1768.0372973	best: 1768.0372973 (500)	total: 2.54s	remaining: 2.53s
550:	learn: 1708.3341473	test: 1762.2208921	best: 1762.2208921 (550)	total: 2.77s	remaining: 2.26s
600:	learn: 1698.4746564	test: 1755.7140033	best: 1755.7140033 (600)	total: 3.02s	remaining: 2s
650:	learn: 1688.7023503	test: 1749.9934750	best: 1749.9934750 (650)	total: 3.25s	remaining: 1.74s
700:	learn: 1679.7950729	test: 1745.0878240	best: 1745.0878240 (700)	total: 3.49s	remaining: 1.49s
750:	learn: 1671.5805643	test: 1740.8678539	best: 1740.8678539 (750)	total: 3.73s	remaining: 1.24s
800:	learn: 1664.3578832	test: 1737.5076500	best: 1737.5076500 (800)	total: 3.97s	remaining: 987ms
850:	learn: 1656.7528616	test: 1733.8270084	best: 1733.8270084 (850)	total: 4.21s	remaining: 737ms
900:	learn: 1649.8612791	test: 1730.8790337	best: 1730.8790337 (900)	total: 4.45s	remaining: 489ms
950:	learn: 1643.1200139	test: 1727.4269311	best: 1727.4269311 (950)	total: 4.68s	remaining: 241ms
999:	learn: 1636.8750640	test: 1724.4013129	best: 1724.4013129 (999)	total: 4.9s	remaining: 0us

bestTest = 1724.401313
bestIteration = 999

In [41]:
# %%

pred_train = model.predict(features_train)
pred_valid = model.predict(features_valid)
pred_test = model.predict(features_test)

In [42]:
# %%
print("Train RMSE:", rmse(target_train, pred_train).round(5))
print("Valid RMSE:", rmse(target_valid, pred_valid).round(5))
print("Test RMSE: ", rmse(target_test, pred_test).round(5))

Train RMSE: 1636.87506
Valid RMSE: 1724.40131
Test RMSE:  1711.01931

In [43]:
# %%

from catboost import CatBoostRegressor

model = CatBoostRegressor(iterations=1000,
                          learning_rate=0.1,
                          metric_period=50)
model.fit(features_train, target_train, 
          eval_set=(features_valid, target_valid))

0:	learn: 4303.6641569	test: 4301.7128896	best: 4301.7128896 (0)	total: 6.1ms	remaining: 6.09s
50:	learn: 2038.0178504	test: 2040.6427778	best: 2040.6427778 (50)	total: 253ms	remaining: 4.7s
100:	learn: 1916.1013000	test: 1924.7826614	best: 1924.7826614 (100)	total: 496ms	remaining: 4.41s
150:	learn: 1861.0469932	test: 1875.5131021	best: 1875.5131021 (150)	total: 757ms	remaining: 4.25s
200:	learn: 1825.3551799	test: 1846.3659885	best: 1846.3659885 (200)	total: 1.01s	remaining: 4.03s
250:	learn: 1798.6495174	test: 1824.8524135	best: 1824.8524135 (250)	total: 1.28s	remaining: 3.81s
300:	learn: 1778.0522977	test: 1809.5490852	best: 1809.5490852 (300)	total: 1.52s	remaining: 3.54s
350:	learn: 1759.2884167	test: 1795.8827617	best: 1795.8827617 (350)	total: 1.79s	remaining: 3.31s
400:	learn: 1743.8840102	test: 1785.3495521	best: 1785.3495521 (400)	total: 2.04s	remaining: 3.05s
450:	learn: 1730.0319854	test: 1775.2968687	best: 1775.2968687 (450)	total: 2.29s	remaining: 2.79s
500:	learn: 1717.6155975	test: 1768.0372973	best: 1768.0372973 (500)	total: 2.53s	remaining: 2.52s
550:	learn: 1708.3341473	test: 1762.2208921	best: 1762.2208921 (550)	total: 2.79s	remaining: 2.27s
600:	learn: 1698.4746564	test: 1755.7140033	best: 1755.7140033 (600)	total: 3.04s	remaining: 2.02s
650:	learn: 1688.7023503	test: 1749.9934750	best: 1749.9934750 (650)	total: 3.28s	remaining: 1.76s
700:	learn: 1679.7950729	test: 1745.0878240	best: 1745.0878240 (700)	total: 3.57s	remaining: 1.52s
750:	learn: 1671.5805643	test: 1740.8678539	best: 1740.8678539 (750)	total: 3.82s	remaining: 1.27s
800:	learn: 1664.3578832	test: 1737.5076500	best: 1737.5076500 (800)	total: 4.06s	remaining: 1.01s
850:	learn: 1656.7528616	test: 1733.8270084	best: 1733.8270084 (850)	total: 4.3s	remaining: 753ms
900:	learn: 1649.8612791	test: 1730.8790337	best: 1730.8790337 (900)	total: 4.54s	remaining: 499ms
950:	learn: 1643.1200139	test: 1727.4269311	best: 1727.4269311 (950)	total: 4.78s	remaining: 246ms
999:	learn: 1636.8750640	test: 1724.4013129	best: 1724.4013129 (999)	total: 5.01s	remaining: 0us

bestTest = 1724.401313
bestIteration = 999

In [44]:
# %%

pred_train = model.predict(features_train)
pred_valid = model.predict(features_valid)
pred_test = model.predict(features_test)

In [45]:
# %%
print("Train RMSE:", rmse(target_train, pred_train).round(5))
print("Valid RMSE:", rmse(target_valid, pred_valid).round(5))
print("Test RMSE: ", rmse(target_test, pred_test).round(5))

Train RMSE: 1636.87506
Valid RMSE: 1724.40131
Test RMSE:  1711.01931

 # 3. Model analysis

 | Model | RMSE | Prediction time, с | Training time, with |

 |----|----|-------|--------|

 | Линейная регрессия | 3220 | 0.156 | 0.4 |

 | LightGBM(1000) | 1640 | 8.47 | 12.9 |

 | CatBoost(1000) | 1730 | 0.899 | 27.2 |





 - The fastest (in training and prediction) model is linear regression. But the quality is low

 - The model with the best quality is gradient boosting LightGBM with 1000 trees.

 - The model with balanced prediction speed and quality is gradient boosting CatBoost with 1000 trees without category processing

In [46]:
# %%